# Generated by Django 6.0.4 on 2026-04-15 13:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="crypto",
            name="date_added",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="crypto",
            name="finnhub_symbol",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Finnhub symbol (e.g. BINANCE:BTCUSDT). Leave blank to skip live tracking.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="date_added",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="stock",
            name="finnhub_symbol",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Finnhub symbol (e.g. AAPL). Leave blank to skip live tracking.",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="PriceAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("target_price", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "direction",
                    models.CharField(
                        choices=[("above", "Above (Sell)"), ("below", "Below (Buy)")],
                        default="above",
                        max_length=5,
                    ),
                ),
                ("email_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "crypto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="assets.crypto",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="assets.stock",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
