# Generated by Django 6.0.4 on 2026-04-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_crypto_date_added_crypto_finnhub_symbol_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricealert",
            name="invest_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="USD amount the user plans to spend when a 'below' (buy) alert triggers. Null for sell alerts.",
                max_digits=18,
                null=True,
            ),
        ),
    ]
