# Generated by Django 6.0.4 on 2026-04-29 07:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_pricealert_invest_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ETF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('finnhub_symbol', models.CharField(blank=True, default='', help_text='Finnhub symbol (e.g. VOO). Leave blank to skip live tracking.', max_length=50)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'ETF',
                'verbose_name_plural': 'ETFs',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='pricealert',
            name='etf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='assets.etf'),
        ),
        migrations.CreateModel(
            name='ETFAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('amount', models.FloatField(default=0.0)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('bought', 'Bought'), ('sold', 'Sold')], default='bought', max_length=10)),
                ('etf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='assets.etf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etf_assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
