# Generated by Django 6.0.4 on 2026-04-29 14:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_etf_pricealert_etf_etfasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ETFSavingsPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='USD amount to invest each interval.', max_digits=18)),
                ('interval', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=10)),
                ('start_date', models.DateField(help_text='Original start date (used to anchor day-of-month). Never changes.')),
                ('next_execution_date', models.DateField(help_text='Next date the plan will auto-execute. Advances after each run.')),
                ('last_executed_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_plans', to='assets.etf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etf_savings_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
