# Generated by Django 6.0.4 on 2026-04-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_etfsavingsplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etf',
            name='finnhub_symbol',
        ),
        migrations.AddField(
            model_name='etf',
            name='last_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='User-maintained last known price (USD). Used for analytics and savings-plan auto-transactions.', max_digits=18, null=True),
        ),
    ]
