# Generated by Django 6.0.4 on 2026-04-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_remove_etf_finnhub_symbol_etf_last_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='etfsavingsplan',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR')], default='USD', help_text='Currency of `amount`. EUR plans are converted to USD at execution time.', max_length=3),
        ),
        migrations.AlterField(
            model_name='etfsavingsplan',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text="Amount to invest each interval, in the plan's currency.", max_digits=18),
        ),
    ]
