# Generated by Django 6.0.4 on 2026-04-30 08:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_cashflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='finnhub_symbol',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cryptoasset',
            name='crypto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_transactions', to='assets.crypto'),
        ),
        migrations.AlterField(
            model_name='etf',
            name='last_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='etfasset',
            name='etf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_transactions', to='assets.etf'),
        ),
        migrations.AlterField(
            model_name='etfsavingsplan',
            name='etf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savings_plans', to='assets.etf'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='finnhub_symbol',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='stockasset',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_transactions', to='assets.stock'),
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('stock', 'Stock'), ('crypto', 'Crypto'), ('etf', 'ETF')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=20)),
                ('finnhub_symbol', models.CharField(blank=True, default='', help_text='Finnhub symbol (e.g. AAPL, BINANCE:BTCUSDT). Leave blank for ETFs or any instrument without a live feed.', max_length=50)),
                ('last_price', models.DecimalField(blank=True, decimal_places=2, help_text='User-maintained last known price (USD). Primarily used for ETFs where there is no live feed; mirrored into the price cache.', max_digits=18, null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'symbol'), name='instrument_unique_kind_symbol'), models.UniqueConstraint(fields=('kind', 'name'), name='instrument_unique_kind_name')],
            },
        ),
        migrations.AddField(
            model_name='etfsavingsplan',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savings_plans', to='assets.instrument'),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='assets.instrument'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('bought', 'Bought'), ('sold', 'Sold')], default='bought', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='assets.instrument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
