# Generated by Django 6.0.4 on 2026-04-30 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_unify_data_copy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptoasset',
            name='crypto',
        ),
        migrations.RemoveField(
            model_name='pricealert',
            name='crypto',
        ),
        migrations.RemoveField(
            model_name='cryptoasset',
            name='user',
        ),
        migrations.RemoveField(
            model_name='etfsavingsplan',
            name='etf',
        ),
        migrations.RemoveField(
            model_name='pricealert',
            name='etf',
        ),
        migrations.RemoveField(
            model_name='etfasset',
            name='etf',
        ),
        migrations.RemoveField(
            model_name='etfasset',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stockasset',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='pricealert',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='stockasset',
            name='user',
        ),
        migrations.AlterField(
            model_name='etfsavingsplan',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_plans', to='assets.instrument'),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='assets.instrument'),
        ),
        migrations.DeleteModel(
            name='Crypto',
        ),
        migrations.DeleteModel(
            name='CryptoAsset',
        ),
        migrations.DeleteModel(
            name='ETF',
        ),
        migrations.DeleteModel(
            name='ETFAsset',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='StockAsset',
        ),
    ]
