# Generated by Django 6.0.4 on 2026-04-30 12:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_add_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('source', models.CharField(choices=[('cache', 'Live cache'), ('finnhub', 'Finnhub candle'), ('coingecko', 'CoinGecko market chart'), ('manual', 'Manual / ETF last_price')], default='cache', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='assets.instrument')),
            ],
            options={
                'ordering': ['instrument', 'date'],
                'constraints': [models.UniqueConstraint(fields=('instrument', 'date'), name='snapshot_unique_instrument_date')],
            },
        ),
    ]
