# Generated by Django 6.0.4 on 2026-05-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_add_price_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Broker commission / network fee (USD). For buys, increases the cost basis. For sells, reduces the realized proceeds. Leave 0 if there's no fee.", max_digits=12),
        ),
    ]
